//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission5Lib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int BookCopyId { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> OverdueDays { get; set; }
        public Nullable<int> OverdueCharge { get; set; }
        public int LibrarianId { get; set; }
    
        public virtual BookCopy BookCopy { get; set; }
        public virtual Librarian Librarian { get; set; }
        public virtual Member Member { get; set; }
    }
}
